version: '3'
services:
  server:
    restart: always
    build: .
    ports:
      - 80:3000
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
    networks:
      - my-kitchen-assistant
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
    networks:
      - my-kitchen-assistant
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - mongodb:/data/db
    networks:
      - my-kitchen-assistant
volumes:
  mongodb:
networks:
  my-kitchen-assistant:
